import { performanceMonitor } from '@/lib/monitoring/performance-monitor'
import { loadBalancer } from '@/lib/monitoring/load-balancer'
import { createRedisCache } from '@/lib/cache/redis-cache'
// import { aiOptimizer } from '@/lib/ai/ai-optimizer'
import { backgroundJobProcessor } from '@/lib/background-job-processor'
import { memoryOptimizer } from '@/lib/memory-optimizer'
import { websocketOptimizer } from '@/lib/websocket-optimizer'
import { logger } from '@/lib/logger'